### PR TITLE
empty constructor

### PR DESCRIPTION
**Pull request by Fire7**
Possibility to initialize port when we need it

### CODE REVIEW

**Comment by Testato** [comment]
Thanks

**Comment by Koepel** [comment]
The constructor does not change the pins and does not initialize them. The pins are remembered in the object, that's all. It was designed this way. Only the Wire.begin() starts to use the pins, and after Wire.end() the pins can be used for others things.
Fire7, do you still think a empty constructor is needed ?
What happens if the functions are used without setting the pins for SDA and SCL ?

**Comment by Fire7** [comment]
@Koepel , what if I use this class in external library ? So I don't know pins (and the count of it) at the moment I initialize another class. It is only for this functionality.

**Comment by Koepel** [comment]
Then it is not about initializing the hardware pins, but about initializing the SoftwareWire object, but I see your point. Could the SoftwareWire functions be called after the empty constructor is called ? Should I add a check, for example if both _sdaPin and _sclPin are zero ? When an Object is created, is the contents defined as all zero as with normal declared variables in 'c' ? I think I have some testing to do.

Could you give an example of such usage ?
The SoftwareWire is not an Arduino Stream object, therefor it might be different if used in another class.
I'm testing the SoftwareWire at the moment against the Arduino Wire library for every possibility, even when it is used in the wrong way, for example a beginTransmission before a requestFrom.

**Comment by Fire7** [comment]
Sorry for a delay (lol :D).
Here is an example.
I've modified original driver:
https://github.com/Fire7/Adafruit_TCS34725_SoftI2C/blob/master/Adafruit_TCS34725softi2c.h#L144
So, while library is initilizating we need only the SoftwareWire object without constants of SDA / SCL pins ( and it won't use any features of SoftwareWire library while SDA, SCL pins are unknown).

Empty constructor here is inly wrapper for usage in external libraries like I did. :)

**Pull request merged**
